spring.application.name=currency-converter
spring.h2.console.enabled=true
spring.datasource.url=jdbc:postgresql://localhost:5432/currency_db
spring.datasource.username=postgres
spring.datasource.password=5636d5ca
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
server.port=8080
